config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resource :chats, only: :create
  get '/chats/:title', to: 'chats#show', as: :chat
  resource :messages, only: :create
  resources :users, only: [:index] do
    resources :private_messages, only: %i[index create]
  end
  root 'chats#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  has_many :messages, -> { sorted }, dependent: :destroy
  belongs_to :user
  before_create { self.title = SecureRandom.hex(3) }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user

  scope :sorted, -> { order(:id) }
  validates :body, presence: true
end

app/models/private_message.rb
# frozen_string_literal: true

class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :recipient, class_name: 'User', foreign_key: 'recipient_id'

  scope :sorted, -> { order(:id) }
  scope :user_messages, lambda { |current_user, user|
    where('(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)',\
          current_user.id, user.id, user.id, current_user.id)
  }
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :chats, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :sent_messages, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'PrivateMessage', foreign_key: 'recipient_id'

  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  def index
    @new_chat = Chat.new
    @chats = Chat.all
  end

  def create
    @new_chat = Chat.new(user: current_user)

    @new_chat.broadcast_append_to :chats if @new_chat&.save
  end

  def show
    @chat = Chat.find_by!(title: params[:title])
    @messages = @chat.messages
    @new_message = current_user&.messages&.build
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  def create
    @new_message = current_user.messages.build(strong_params)

    @new_message.broadcast_append_to @new_message.chat if @new_message.save
  end

  private

  def strong_params
    params.require(:message).permit(:chat_id, :body)
  end
end

app/controllers/private_messages_controller.rb
# frozen_string_literal: true

class PrivateMessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @private_message = PrivateMessage.new(private_message_params)
    @private_message.sender_id = current_user.id

    @private_message.broadcast_append_to :private_messages if @private_message.save
  end

  def index
    @user = User.find(params[:user_id])
    @private_messages = PrivateMessage.user_messages(current_user, @user)
    @private_message = PrivateMessage.new
  end

  private

  def private_message_params
    params.require(:private_message).permit(:body, :recipient_id)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/chats/_chat.html.erb
<%= link_to chat.title, chat_path(chat.title), class: "text-primary text-decoration-none me-4", target: "_blank", rel: "noopener noreferrer" %>

app/views/chats/index.html.erb
<%= turbo_stream_from :chats %>

<div id="chats" class="container">
  <%= render @chats %>
</div>

<% if current_user.present? %>
  <%= form_with model: @new_chat do |f| %>
    <%= f.submit "Create chat", class: "btn btn-primary mt-3" %>
  <% end %>
<% end %>

app/views/chats/show.html.erb
<%= turbo_stream_from @chat %>
<%= turbo_stream_from [current_user, @chat] %>

<div class="d-flex flex-column h-100 justify-content-between">
  <div class="my-2 overflow-x-auto mx-sm-6 mx-lg-8" id="chat-container">
    <div class="py-2 align-middle inline-block w-100 px-sm-6 px-lg-8" id="chat_<%= @chat.id %>_messages">
      <%= turbo_frame_tag :messages do %>
        <%= render @messages %>
      <% end %>
    </div>
  </div>
</div>

<%= form_with model: @new_message, data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" } do |f| %>
  <div class="mb-3">
    <%= f.text_area :body, autofocus: true, required: true, placeholder: "Your text", class: "form-control" %>
  </div>
  <%= f.hidden_field :chat_id, value: @chat.id %>
  <%= f.submit 'Send', class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="dark">
<head>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Online chat</title>

    <style>
      body {
        margin-left: 20rem;
        margin-right: 20rem;
      }
    </style>

    </head>
  <body class="d-flex h-100 text-center text-bg-dark">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
      </symbol>
    </svg>

    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Online chat</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">

         <%= link_to "Home", root_path, class: "nav-link fw-bold py-1 px-3" %>
        <% if user_signed_in? %>
          <%= link_to "Private message", users_path, class: "nav-link fw-bold py-1 px-3" %>
          <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link fw-bold py-1 px-0" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "nav-link fw-bold py-1 px-3" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link fw-bold py-1 px-3" %>
         <% end %>
      </nav>
    </div>
  </header>

  <main class="px-3"style="height: 80vh; overflow-y: auto;">
    <%= yield %>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Online chat on ROR, by <a href="https://t.me/Edlayli" class="text-white">@Edlayli</a>.</p>
  </footer>
</div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="card shadow overflow-hidden border-0 mb-4">
  <div class="card-body">
    <div class="row">
      <div class="col-2"><%= l(message.created_at, format: :short) %></div>
      <div class="col-3"><%= message.user.email %></div>
      <div class="col-7"><%= message.body %></div>
    </div>
  </div>
</div>

app/views/private_messages/_form.html.erb
<%= form_with(model: private_message, url: user_private_messages_path(user), method: 'post', data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" }) do |form| %>
  <div class="mb-3">
    <%= form.hidden_field :recipient_id, value: user.id %>
    <%= form.text_field :body, autofocus: true, required: true, placeholder: "Your text", class: "form-control" %>
  </div>
  <%= form.submit 'Send', class: "btn btn-primary" %>
<% end %>

app/views/private_messages/_private_message.html.erb
<div class="card shadow overflow-hidden border-0 mb-4">
  <div class="card-body">
    <div class="row">
      <div class="col-2"><%= l(private_message.created_at, format: :short) %></div>
      <div class="col-3"><%= private_message.sender.email %></div>
      <div class="col-7"><%= private_message.body %></div>
    </div>
  </div>
</div>

app/views/private_messages/index.html.erb
<%= turbo_stream_from :private_messages %>

<h1>История сообщений с <%= @user.email %></h1>

<div class="d-flex flex-column h-100 justify-content-between">
  <div class="my-2 overflow-x-auto mx-sm-6 mx-lg-8" id="chat-container">
    <div class="py-2 align-middle inline-block w-100 px-sm-6 px-lg-8">
      <%= turbo_frame_tag :private_messages do %>
        <div id="messages-container">
          <%= render partial: 'private_messages/private_message', collection: @private_messages %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'form', locals: { user: @user, private_message: @private_message } %>

app/views/users/index.html.erb
<h1>Пользователи</h1>
<% @users.each do |user| %>
  <%= link_to user.email, user_private_messages_path(user) %><br>
<% end %>